blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<slug:slug>/', views.post_detail, name='post_detail'),
    path('<slug:slug>/edit_comment/<int:comment_id>',
         views.comment_edit, name='comment_edit'),
    path('<slug:slug>/delete_comment/<int:comment_id>',
         views.comment_delete, name='comment_delete'),
     path('', views.PostList.as_view(), name='blog'),
]

runs/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.RunList.as_view(), name='runs'),
    path('<slug:slug>/', views.RunDetail.as_view(), name='run_detail'),
    path('runs/my-bookings/', views.MyBookings.as_view(), 
         name='my_bookings'),
    path('delete/<int:pk>/', views.BookingDeleteView.as_view(), 
         name='delete_booking'),
    path('update/<int:pk>/', views.BookingUpdateView.as_view(), 
         name='update_booking')
]

runtribe/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'), name='blog-urls'),
    path('runs/', include('runs.urls'), name='runs-urls'),
    path('user_profile/', include('user_profile.urls'), name='user_profile-urls'),
    path('summernote/', include('django_summernote.urls')),
    path("", include('home.urls'), name='home-urls'),]

runs/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


STATUS = ((0, 'Draft'), (1, 'Published'))


class Runs(models.Model):
    """
    Stores a run entry related to :model: `runs.Runs`.
    """
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    featured_image = CloudinaryField('image', default='placeholder')
    description = models.TextField()
    excerpt = models.TextField(blank=True)
    status = models.IntegerField(choices=STATUS, default=0)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Runs'

    def __str__(self):
        return f"Run - {self.title}"


class Booking(models.Model):
    """
     Model representing a booking made by a user for a specific run
     Store a booking made by the user related to 
     :model: `runs.Booking` and :model: `runs.Runs`
    """
    run = models.ForeignKey(
        Runs, on_delete=models.CASCADE, related_name='run_booking')
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user_booking')
    approved = models.BooleanField(default=False)
    phone = models.CharField(max_length=12, blank=True)

    def __str__(self):
        return f'{self.run.title} is booked by {self.user}'

runs/forms.py
from django import forms
from .models import Booking


class BookingForm(forms.ModelForm):
    """
    form for booking runs
    """
    class Meta:
        """
        model for form and fields for form edit
        """
        model = Booking
        fields = ('phone',)

runs/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic, View
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import DeleteView, UpdateView
from .models import Runs, Booking
from .forms import BookingForm


class RunList(generic.ListView):
    """
    Displays a list of runs that have been marked as
    published by the admin
    Retrieves data for each run from :model:`runs.Runs`.
    Diplays the runs list of 8 posts per page
    **Template**
    :template:`runs/runs.html`
    """
    queryset = Runs.objects.filter(status=1)
    template_name = "runs/runs.html"
    paginate_by = 8


class RunDetail(View):
    """
    View for displaying details of a run and handling bookings
    **Context**
    ``run``
        an instance of :model:`runs.Runs`
    ``booking_form``
        an instance of :form:`runs.BookingForm
    ``booking``
        bookings related to each booking
    **Template:**
    :template:`runs/book_runs.html`
    """

    def get(self, request, slug, *args, **kwargs):

        queryset = Runs.objects.all()
        run = get_object_or_404(queryset, slug=slug)

        return render(
            request,
            "runs/book_run.html",
            {
                "run": run,
                "booking_form": BookingForm()
            },
        )

    def post(self, request, slug, *args, **kwargs):

        queryset = Runs.objects.all()
        run = get_object_or_404(queryset, slug=slug)

        booking_form = BookingForm(data=request.POST)
        if booking_form.is_valid():

            booking_form.instance.user = request.user
            booking = booking_form.save(commit=False)
            booking_form.instance.run = run
            booking_form.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Your booking is awaiting approval.'
                'Book more runs at the runs page or '
                'view your booking in the My Bookings page'
            )

        booking_form = BookingForm()
        return render(
            request,
            "runs/book_run.html",
            {
                "run": run,
                "booking_form": booking_form
            },
        )


class MyBookings(generic.ListView):
    """
    renders the my booking page with users booking
    from :model:`runs.Booking`.
    **Context**
    ``user_bookings``
        An instance of :model:`runs.Booking`
    **Template:**
    :template:`runs/my_bookings.html`
    """
    def get(self, request):
        """ My Bookings page """
        user_bookings = Booking.objects.filter(user=request.user)
        return render(request, 'runs/my_bookings.html', {
                'user_bookings': user_bookings,
                'approved': True,
            })


class BookingDeleteView(SuccessMessageMixin, DeleteView):
    """
    Allows user to delete their booking for a run
    Updates the data in :model:`runs.Booking`
    On deletion redirects user to homepage
    Displays success messaged to user
    **Template:**
    :template:`runs/booking_confirm_delete.html`
    """
    model = Booking
    template_name = "runs/booking_confirm_delete.html"
    success_url = "/"
    success_message = "You have successfully been removed from this run."

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(BookingDeleteView, self).delete(request, *args, **kwargs)


class BookingUpdateView(SuccessMessageMixin, UpdateView):
    """
    Allows user to update their contact details
    on a booking for a run
    Updates the data in :model:`runs.Booking`
    On update redirects user to homepage
    Displays success messaged to user
    **Context**
    ``fields``
        an instance of :form:`runs.BookingForm
    **Template:**
    :template:`runs/booking_update.html`
    """
    model = Booking
    template_name = "runs/booking_update.html"
    success_url = "/"
    success_message = "Your contact details have been updated, thanks."
    fields = [
        "phone",
    ]

runs/templates/runs/book_run.html
{% extends 'base.html' %} 
{% block content %} 
{% load static %} 
{% load crispy_forms_tags %}

<!-- book_run.html content starts here -->
<!-- displays django messages -->
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      {% for message in messages %}
      <div
        class="alert {{ message.tags }} alert-dismissible
        fade show"
        id="msg"
        role="alert"
      >
        {{ message | safe }}
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="alert"
          aria-label="Close"
        ></button>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
<!-- information about the run will be displayed from  here -->
<div class="container">
  <div class="row">
    <div class="col card mb-4 mt-3 left top">
      <div class="card-body">
        <div class="image-container">
          <!-- dispalys image for run -->
          {% if "placeholder" in run.featured_image.url %}
          <!-- displays default placeholder image -->
          <img class="card-img-top" src="{% static 'images/default_runs_image.webp' %}" alt="placeholder image">
          {% else %}
          <!-- displays image uploaded to run information -->
          <img class="card-img-top" src=" {{ run.featured_image.url }}" alt="{{ run.title }}">
          {% endif %}
      </div>
      <!-- run title displays here -->
        <h2>{{ run.title | safe }}</h2>
        <!-- run description goes here -->
        <article class="card-text">{{ run.description | safe }}</article>
      </div>
    </div>
  </div>
</div>
<!-- run booking section -->
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-4 card mb-4 mt-3 mx-auto">
      <div class="card-body">
        <h3>Book run:</h3>
        <!-- provides user details currently logged in as -->
        <p>Add {{ user.username }} to this run group.</p>
        <p> Please enter a contact number below incase the run organiser needs to get in touch.</p>
        <!-- booking form -->
        <form method="post" style="margin-top: 1.3em">
          {{ booking_form | crispy }} {% csrf_token %}
          <button id="submitButton" type="submit" class="btn btn-signup btn-lg">
            Book
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- book_run.html ends here -->
{% endblock %}

runs/templates/runs/booking_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<!-- booking_confirm_delete.html content starts here -->
<div class="container-fluid">
    <div class="row text-center">
        <!-- header -->
        <h2>Cancel your booking</h2>

        <div class="container">
            <div class="col-12 mt-3">
                <div class="row card-deck">
                    <!-- form to delete booking -->
                    <form method="post">{% csrf_token %}
                        <p>Are you sure you want to cancel your place for "{{ booking.run.title }}"?</p>
                        <input class="btn btn-danger mb-4 mt-4" type="submit" value="Confirm">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- booking_confirm_delete.html content ends here -->
{% endblock %}

runs/templates/runs/booking_update.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<!-- displays booking_update.html content from here -->
<div class="container text-center">
  <div class="row">
    <!-- header -->
    <h2>Make a change to your booking contact details below <i class="fas fa-arrow-down"></i></h2>
  </div>
</div>
<!-- update booking section -->
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-4 card mb-4 mt-3 mx-auto">
      <div class="card-body">
        <h3>Amend runners contact details:</h3>
        <p>Runner: {{ user.username }}</p>
        <!-- form to update booking -->
        <form method="post" style="margin-top: 1.3em">
          {{ form | crispy }}
          {% csrf_token %}
          <button id="submitButton" type="submit" class="btn btn-signup btn-lg">
            Update
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- booking_update.html content ends here -->
{% endblock %}

runs/templates/runs/my_bookings.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<!-- my_bookings.html content starts here -->
<!-- displays django messages -->
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible
        fade show" id="msg" role="alert">
                {{ message | safe }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- header and booking information section -->
<div class="container-fluid">
    <div class="row">
        <h2>Lace up your shoes, you've got running to do</h2>
        <!-- each booking displayed here on a seperate card -->
        <div class="container">
            <div class="col-12 mt-3">
                <div class="row card-deck">
                    <!-- loops through and displays each booking made by user -->
                    {% for booking in user_bookings %}
                    <div class="col-md-3">
                        <div class="card mb-2">
                            <div class="card-body">
                                <!-- provides feedback to the user if booking is confirmed or pending -->
                                {% if not booking.approved and booking.user == user %}
                                <p class="pending">
                                    This booking is with admin for approval...
                                </p>
                                {% elif booking.approved and booking.user == user %}
                                <p class="approval">
                                    This booking has been confirmed <i class="fas fa-running approval_icon"></i>
                                </p>
                                {% endif %}
                                <!-- displays booking title and option to delete/edit -->
                                <h4>{{ booking.run.title | safe }}</h4>
                                <p>{{ booking.run.excerpt | safe }}</p>
                                <a href="{% url 'update_booking' booking.id %}" class="btn btn-edit mb-4 mt-4">Update
                                    Booking</a>
                                <a href="{% url 'delete_booking' booking.id %}" class="btn btn-danger mb-4 mt-4">Delete
                                    Booking</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

<!-- my_bookings.html content ends here -->
{% endblock %}

runs/templates/runs/runs.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<!-- runs.html content starts here -->
<div class="container-fluid">
  <div class="row text-center">
    <h2 class="title-text">Let's get running <i class="fas fa-running"></i></h2>
    <div class="container">
      <section class="col-12 mt-3">
        <div class="row card-deck">
          <!-- loops through and publishes each approved run -->
          {% for run in runs_list %}
          <div class="col-md-3">
            <div class="card mb-2">
              <div class="card-body">
                <h4 class="title-text">{{ run.title | safe }}</h4>
                <article class="text-center">{{ run.excerpt | safe }}</article>
                <!-- if user logged in allows them to view more information about a run -->
                {% if user.is_authenticated %}
                <a href="{% url 'run_detail' run.slug %}" class="btn btn-book">More Information</a>
                {% else %}
                <!-- if not logged in user prompted to log in or create an account -->
                <p>If you are already a member of the tribe then please <a class="link" href="{{ login_url }}">sign
                    in</a> to book a space with this running group</p>
                <p>If you haven't created an account yet then <a class="link" href="{{ signup_url }}">sign up</a>
                  first.</p>
                {% endif %}
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </section>
    </div>
  </div>
  <!-- if runs continue to another page this allows user to navigate to next/prev page -->
  {% if is_paginated %}
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li>
        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV</a>
      </li>
      {% endif %} {% if page_obj.has_next %}
      <li>
        <a href="?page={{ page_obj.next_page_number }}" class="page-link">
          NEXT &raquo;</a>
      </li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
</div>

<!-- runs.html content ends here -->
{% endblock %}